# Generated by Django 4.2.21 on 2025-06-08 09:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('family', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('national_code', models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'کد ملی باید ۱۰ رقم باشد.')], verbose_name='کد ملی')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('gender', models.CharField(choices=[('male', 'مرد'), ('female', 'زن')], default='other', max_length=10, verbose_name='جنسیت')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'فرمت شماره تماس نامعتبر است.')], verbose_name='شماره تماس')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='کد پستی')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='authors/', verbose_name='عکس پروفایل')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='بیوگرافی')),
                ('expertise', models.CharField(blank=True, max_length=255, null=True, verbose_name='زمینه فعالیت/تخصص')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'نویسنده',
                'verbose_name_plural': 'نویسندگان',
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام کانال')),
                ('channel_id', models.CharField(max_length=100, unique=True, verbose_name='آیدی کانال')),
                ('topic', models.CharField(max_length=100, verbose_name='موضوع')),
                ('sub_topic', models.CharField(max_length=100, verbose_name='زیر موضوع')),
                ('audience', models.CharField(max_length=100, verbose_name='مخاطب')),
                ('created_at', models.DateField(verbose_name='تاریخ ایجاد')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='channel_pictures/', verbose_name='عکس کانال')),
            ],
            options={
                'verbose_name': 'کانال',
                'verbose_name_plural': 'کانال\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام پلتفرم')),
                ('logo', models.ImageField(upload_to='platform_logos/', verbose_name='لوگو')),
            ],
            options={
                'verbose_name': 'پلتفرم',
                'verbose_name_plural': 'پلتفرم\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام استان')),
            ],
            options={
                'verbose_name': 'استان',
                'verbose_name_plural': 'استان\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_text', models.TextField(verbose_name='متن پست')),
                ('hashtags', models.TextField(verbose_name='هشتگ\u200cها')),
                ('views', models.PositiveIntegerField(verbose_name='تعداد بازدید')),
                ('collected_at', models.DateField(verbose_name='تاریخ جمع\u200cآوری')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporter.author', verbose_name='نویسنده')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='reporter.channel', verbose_name='کانال')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست\u200cها',
            },
        ),
        migrations.CreateModel(
            name='ChannelMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_count', models.PositiveIntegerField(verbose_name='تعداد عضو')),
                ('collected_at', models.DateField(verbose_name='تاریخ جمع\u200cآوری')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='reporter.channel', verbose_name='کانال')),
            ],
            options={
                'verbose_name': 'عضویت کانال',
                'verbose_name_plural': 'عضویت کانال\u200cها',
            },
        ),
        migrations.AddField(
            model_name='channel',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporter.platform', verbose_name='پلتفرم'),
        ),
        migrations.AddField(
            model_name='channel',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reporter.province', verbose_name='استان'),
        ),
        migrations.AddField(
            model_name='author',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reporter.province', verbose_name='استان'),
        ),
    ]
