# Generated by Django 4.2.21 on 2025-07-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_access_panel',
            field=models.BooleanField(default=False, verbose_name='دسترسی به پنل'),
        ),
    ]
