# Generated by Django 4.2.21 on 2025-07-08 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reporter', '0003_userprofile_can_access_panel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='پیام')),
                ('status', models.CharField(choices=[('open', 'باز'), ('in_progress', 'در حال بررسی'), ('resolved', 'حل شده'), ('closed', 'بسته شده')], default='open', max_length=20, verbose_name='وضعیت')),
                ('priority', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'بالا'), ('critical', 'بحرانی')], default='medium', max_length=20, verbose_name='اولویت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('admin_response', models.TextField(blank=True, null=True, verbose_name='پاسخ ادمین')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تیکت',
                'verbose_name_plural': 'تیکت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'دسترسی پنل', 'verbose_name_plural': 'دسترسی پنل'},
        ),
        migrations.CreateModel(
            name='TicketResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_admin', models.BooleanField(default=False, verbose_name='پاسخ ادمین')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='reporter.ticket', verbose_name='تیکت')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پاسخ تیکت',
                'verbose_name_plural': 'پاسخ\u200cهای تیکت',
                'ordering': ['created_at'],
            },
        ),
    ]
