# Generated by Django 4.2.21 on 2025-07-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0005_remove_ticketresponse_ticket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='chat_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Chat ID'),
        ),
        migrations.AddField(
            model_name='post',
            name='chat_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Chat Type'),
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ارسال پیام'),
        ),
        migrations.AddField(
            model_name='post',
            name='document_file_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Document File ID'),
        ),
        migrations.AddField(
            model_name='post',
            name='document_file_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Document File Name'),
        ),
        migrations.AddField(
            model_name='post',
            name='document_file_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Document File Size'),
        ),
        migrations.AddField(
            model_name='post',
            name='document_file_unique_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Document Unique ID'),
        ),
        migrations.AddField(
            model_name='post',
            name='document_mime_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Document MIME Type'),
        ),
        migrations.AddField(
            model_name='post',
            name='entities',
            field=models.JSONField(blank=True, null=True, verbose_name='Entities'),
        ),
        migrations.AddField(
            model_name='post',
            name='forward_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Forward Date'),
        ),
        migrations.AddField(
            model_name='post',
            name='forward_from_chat_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Forward From Chat ID'),
        ),
        migrations.AddField(
            model_name='post',
            name='forward_from_chat_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Forward From Chat Title'),
        ),
        migrations.AddField(
            model_name='post',
            name='forward_from_chat_username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Forward From Chat Username'),
        ),
        migrations.AddField(
            model_name='post',
            name='forward_from_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Forward From ID'),
        ),
        migrations.AddField(
            model_name='post',
            name='forward_from_message_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Forward From Message ID'),
        ),
        migrations.AddField(
            model_name='post',
            name='forward_from_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Forward From Name'),
        ),
        migrations.AddField(
            model_name='post',
            name='forward_from_username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Forward From Username'),
        ),
        migrations.AddField(
            model_name='post',
            name='forward_origin_sender_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Forward Origin Sender ID'),
        ),
        migrations.AddField(
            model_name='post',
            name='forward_origin_sender_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Forward Origin Sender Name'),
        ),
        migrations.AddField(
            model_name='post',
            name='forward_origin_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Forward Origin Type'),
        ),
        migrations.AddField(
            model_name='post',
            name='has_media',
            field=models.BooleanField(default=False, verbose_name='دارای مدیا'),
        ),
        migrations.AddField(
            model_name='post',
            name='message_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Message ID'),
        ),
        migrations.AddField(
            model_name='post',
            name='photo_file_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Photo File ID'),
        ),
        migrations.AddField(
            model_name='post',
            name='photo_file_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Photo File Size'),
        ),
        migrations.AddField(
            model_name='post',
            name='photo_file_unique_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Photo Unique ID'),
        ),
        migrations.AddField(
            model_name='post',
            name='photo_height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Photo Height'),
        ),
        migrations.AddField(
            model_name='post',
            name='photo_width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Photo Width'),
        ),
        migrations.AddField(
            model_name='post',
            name='reply_to_message_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Reply To Message ID'),
        ),
        migrations.AddField(
            model_name='post',
            name='sender_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Sender ID'),
        ),
        migrations.AddField(
            model_name='post',
            name='sender_is_bot',
            field=models.BooleanField(default=False, verbose_name='Is Bot'),
        ),
        migrations.AddField(
            model_name='post',
            name='sender_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sender Name'),
        ),
        migrations.AddField(
            model_name='post',
            name='sender_username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sender Username'),
        ),
        migrations.AddField(
            model_name='post',
            name='update_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Update ID'),
        ),
        migrations.AddField(
            model_name='post',
            name='video_duration',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Video Duration'),
        ),
        migrations.AddField(
            model_name='post',
            name='video_file_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Video File ID'),
        ),
        migrations.AddField(
            model_name='post',
            name='video_file_size',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Video File Size'),
        ),
        migrations.AddField(
            model_name='post',
            name='video_file_unique_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Video Unique ID'),
        ),
        migrations.AddField(
            model_name='post',
            name='video_height',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Video Height'),
        ),
        migrations.AddField(
            model_name='post',
            name='video_width',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Video Width'),
        ),
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
    ]
