# Generated by Django 4.2.21 on 2025-07-12 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0006_post_chat_id_post_chat_type_post_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='username',
            field=models.CharField(default='', max_length=100, verbose_name='نام کاربری'),
            preserve_default=False,
        ),
    ]
