# Generated by Django 4.2.21 on 2025-07-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0007_author_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='hashtags',
            field=models.TextField(blank=True, null=True, verbose_name='هشتگ\u200cها'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_text',
            field=models.TextField(blank=True, null=True, verbose_name='متن پست'),
        ),
    ]
