# Generated by Django 4.2.21 on 2025-07-08 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='sender',
            new_name='messenger',
        ),
    ]
