# Generated by Django 4.2.21 on 2025-07-08 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_rename_sender_notification_messenger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='messenger',
        ),
    ]
