# Generated by Django 4.2.21 on 2025-07-08 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_remove_notification_messenger'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
