# Generated by Django 4.2.21 on 2025-07-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(verbose_name='محتوا'),
        ),
    ]
