# Generated by Django 4.2.21 on 2025-07-09 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0008_role_memberprofile_generalnotice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalnotice',
            name='main_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notices', to='support.memberprofile'),
        ),
        migrations.AlterField(
            model_name='generalnotice',
            name='receivers',
            field=models.ManyToManyField(blank=True, related_name='received_notices', to='support.memberprofile'),
        ),
    ]
