# Generated by Django 4.2.21 on 2025-07-09 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0009_alter_generalnotice_main_member_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberprofile',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='role',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='GeneralNotice',
        ),
        migrations.DeleteModel(
            name='MemberProfile',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
