# Generated by Django 4.2.21 on 2025-06-17 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0021_post_author_post_hashtags_post_titr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='hashtags',
        ),
        migrations.RemoveField(
            model_name='post',
            name='titr',
        ),
    ]
