# Generated by Django 4.2.21 on 2025-06-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0022_remove_post_author_remove_post_hashtags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='type',
            field=models.CharField(choices=[('group', 'Group'), ('channel', 'Channel')], default='channel', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.TextField(verbose_name='پیام'),
        ),
        migrations.AlterField(
            model_name='post',
            name='channels',
            field=models.ManyToManyField(to='sender.channel', verbose_name='انتخاب کانال'),
        ),
        migrations.AlterField(
            model_name='post',
            name='scheduled_time',
            field=models.DateTimeField(verbose_name='زمانبندی'),
        ),
    ]
